//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationClient.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineStationBase", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class LineStationBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentProductName {
            get {
                return this.CurrentProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentProductNameField, value) != true)) {
                    this.CurrentProductNameField = value;
                    this.RaisePropertyChanged("CurrentProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Frame", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class Frame : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductBase", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class ProductBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationRealtimeData", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class StationRealtimeData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogistTailElem", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class LogistTailElem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TailStationIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TailStationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchName {
            get {
                return this.BatchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchNameField, value) != true)) {
                    this.BatchNameField = value;
                    this.RaisePropertyChanged("BatchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchType {
            get {
                return this.BatchTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchTypeField, value) != true)) {
                    this.BatchTypeField = value;
                    this.RaisePropertyChanged("BatchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TailStationIndex {
            get {
                return this.TailStationIndexField;
            }
            set {
                if ((this.TailStationIndexField.Equals(value) != true)) {
                    this.TailStationIndexField = value;
                    this.RaisePropertyChanged("TailStationIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TailStationName {
            get {
                return this.TailStationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TailStationNameField, value) != true)) {
                    this.TailStationNameField = value;
                    this.RaisePropertyChanged("TailStationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogMessage", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class LogMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlertTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EventTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlertType {
            get {
                return this.AlertTypeField;
            }
            set {
                if ((this.AlertTypeField.Equals(value) != true)) {
                    this.AlertTypeField = value;
                    this.RaisePropertyChanged("AlertType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EventTime {
            get {
                return this.EventTimeField;
            }
            set {
                if ((this.EventTimeField.Equals(value) != true)) {
                    this.EventTimeField = value;
                    this.RaisePropertyChanged("EventTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line {
            get {
                return this.LineField;
            }
            set {
                if ((object.ReferenceEquals(this.LineField, value) != true)) {
                    this.LineField = value;
                    this.RaisePropertyChanged("Line");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageString {
            get {
                return this.MessageStringField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageStringField, value) != true)) {
                    this.MessageStringField = value;
                    this.RaisePropertyChanged("MessageString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjName {
            get {
                return this.ObjNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjNameField, value) != true)) {
                    this.ObjNameField = value;
                    this.RaisePropertyChanged("ObjName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType {
            get {
                return this.ObjectTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectTypeField, value) != true)) {
                    this.ObjectTypeField = value;
                    this.RaisePropertyChanged("ObjectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientInstruction", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class ClientInstruction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentUrl {
            get {
                return this.ContentUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentUrlField, value) != true)) {
                    this.ContentUrlField = value;
                    this.RaisePropertyChanged("ContentUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogistRequestElem", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class LogistRequestElem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StationIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WaitingTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNum {
            get {
                return this.OrderNumField;
            }
            set {
                if ((this.OrderNumField.Equals(value) != true)) {
                    this.OrderNumField = value;
                    this.RaisePropertyChanged("OrderNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartName {
            get {
                return this.PartNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNameField, value) != true)) {
                    this.PartNameField = value;
                    this.RaisePropertyChanged("PartName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StationIndex {
            get {
                return this.StationIndexField;
            }
            set {
                if ((this.StationIndexField.Equals(value) != true)) {
                    this.StationIndexField = value;
                    this.RaisePropertyChanged("StationIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationName {
            get {
                return this.StationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StationNameField, value) != true)) {
                    this.StationNameField = value;
                    this.RaisePropertyChanged("StationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WaitingTime {
            get {
                return this.WaitingTimeField;
            }
            set {
                if ((this.WaitingTimeField.Equals(value) != true)) {
                    this.WaitingTimeField = value;
                    this.RaisePropertyChanged("WaitingTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogisticInfo", Namespace="http://schemas.datacontract.org/2004/07/LineService")]
    [System.SerializableAttribute()]
    public partial class LogisticInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextBatchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaktsTillNextBatchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineId {
            get {
                return this.LineIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LineIdField, value) != true)) {
                    this.LineIdField = value;
                    this.RaisePropertyChanged("LineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextBatchName {
            get {
                return this.NextBatchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NextBatchNameField, value) != true)) {
                    this.NextBatchNameField = value;
                    this.RaisePropertyChanged("NextBatchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaktsTillNextBatch {
            get {
                return this.TaktsTillNextBatchField;
            }
            set {
                if ((this.TaktsTillNextBatchField.Equals(value) != true)) {
                    this.TaktsTillNextBatchField = value;
                    this.RaisePropertyChanged("TaktsTillNextBatch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IAssembLine")]
    public interface IAssembLine {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/Execute", ReplyAction="http://tempuri.org/IAssembLine/ExecuteResponse")]
        void Execute();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/Terminate", ReplyAction="http://tempuri.org/IAssembLine/TerminateResponse")]
        void Terminate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/ResetTimer", ReplyAction="http://tempuri.org/IAssembLine/ResetTimerResponse")]
        void ResetTimer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/Move", ReplyAction="http://tempuri.org/IAssembLine/MoveResponse")]
        void Move();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/FinishStation", ReplyAction="http://tempuri.org/IAssembLine/FinishStationResponse")]
        void FinishStation(string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetState", ReplyAction="http://tempuri.org/IAssembLine/GetStateResponse")]
        int GetState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetCounter", ReplyAction="http://tempuri.org/IAssembLine/GetCounterResponse")]
        int GetCounter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetCounter", ReplyAction="http://tempuri.org/IAssembLine/SetCounterResponse")]
        void SetCounter(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetCounterForever", ReplyAction="http://tempuri.org/IAssembLine/SetCounterForeverResponse")]
        void SetCounterForever(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetStations", ReplyAction="http://tempuri.org/IAssembLine/GetStationsResponse")]
        StationClient.ServiceReference2.LineStationBase[] GetStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetStationsArray", ReplyAction="http://tempuri.org/IAssembLine/GetStationsArrayResponse")]
        StationClient.ServiceReference2.LineStationBase[] GetStationsArray();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/RemoveStation", ReplyAction="http://tempuri.org/IAssembLine/RemoveStationResponse")]
        void RemoveStation(string LineStationRemoveId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/PushStationButton", ReplyAction="http://tempuri.org/IAssembLine/PushStationButtonResponse")]
        int PushStationButton(int StationIndex, string ControlKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/ReadStationButton", ReplyAction="http://tempuri.org/IAssembLine/ReadStationButtonResponse")]
        string ReadStationButton(int StationIndex, string ControlKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/ReadStationName", ReplyAction="http://tempuri.org/IAssembLine/ReadStationNameResponse")]
        string ReadStationName(int StationIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetOPCMode", ReplyAction="http://tempuri.org/IAssembLine/SetOPCModeResponse")]
        void SetOPCMode(bool mode, string OPCServerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetOPCMode", ReplyAction="http://tempuri.org/IAssembLine/GetOPCModeResponse")]
        bool GetOPCMode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/ReadProduct", ReplyAction="http://tempuri.org/IAssembLine/ReadProductResponse")]
        string ReadProduct(int StationIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/ReadFrame", ReplyAction="http://tempuri.org/IAssembLine/ReadFrameResponse")]
        StationClient.ServiceReference2.Frame ReadFrame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetProductStock", ReplyAction="http://tempuri.org/IAssembLine/GetProductStockResponse")]
        StationClient.ServiceReference2.ProductBase[] GetProductStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetProductBuffer", ReplyAction="http://tempuri.org/IAssembLine/GetProductBufferResponse")]
        StationClient.ServiceReference2.ProductBase[] GetProductBuffer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetStationBuffer", ReplyAction="http://tempuri.org/IAssembLine/GetStationBufferResponse")]
        StationClient.ServiceReference2.ProductBase[] GetStationBuffer(int stationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/ReadRealTimeData", ReplyAction="http://tempuri.org/IAssembLine/ReadRealTimeDataResponse")]
        StationClient.ServiceReference2.StationRealtimeData[] ReadRealTimeData(int StationIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/ReadRealTimeDataForLine", ReplyAction="http://tempuri.org/IAssembLine/ReadRealTimeDataForLineResponse")]
        StationClient.ServiceReference2.StationRealtimeData[] ReadRealTimeDataForLine(int StationIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetLogisticTails", ReplyAction="http://tempuri.org/IAssembLine/GetLogisticTailsResponse")]
        StationClient.ServiceReference2.LogistTailElem[] GetLogisticTails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetSumStopTime", ReplyAction="http://tempuri.org/IAssembLine/GetSumStopTimeResponse")]
        int GetSumStopTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/RestoreLine", ReplyAction="http://tempuri.org/IAssembLine/RestoreLineResponse")]
        void RestoreLine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetOPCRestarted", ReplyAction="http://tempuri.org/IAssembLine/SetOPCRestartedResponse")]
        void SetOPCRestarted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetStationDayPlan", ReplyAction="http://tempuri.org/IAssembLine/SetStationDayPlanResponse")]
        void SetStationDayPlan(string stationName, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetStationMonthPlan", ReplyAction="http://tempuri.org/IAssembLine/SetStationMonthPlanResponse")]
        void SetStationMonthPlan(string stationName, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetStationDayFact", ReplyAction="http://tempuri.org/IAssembLine/SetStationDayFactResponse")]
        void SetStationDayFact(string stationName, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetStationMonthFact", ReplyAction="http://tempuri.org/IAssembLine/SetStationMonthFactResponse")]
        void SetStationMonthFact(string stationName, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetMemLogData", ReplyAction="http://tempuri.org/IAssembLine/GetMemLogDataResponse")]
        StationClient.ServiceReference2.LogMessage[] GetMemLogData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/GetClientInstruction", ReplyAction="http://tempuri.org/IAssembLine/GetClientInstructionResponse")]
        StationClient.ServiceReference2.ClientInstruction GetClientInstruction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssembLine/SetClientInstruction", ReplyAction="http://tempuri.org/IAssembLine/SetClientInstructionResponse")]
        void SetClientInstruction(int Mode, string ContentUrl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssembLineChannel : StationClient.ServiceReference2.IAssembLine, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssembLineClient : System.ServiceModel.ClientBase<StationClient.ServiceReference2.IAssembLine>, StationClient.ServiceReference2.IAssembLine {
        
        public AssembLineClient() {
        }
        
        public AssembLineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssembLineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssembLineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssembLineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Execute() {
            base.Channel.Execute();
        }
        
        public void Terminate() {
            base.Channel.Terminate();
        }
        
        public void ResetTimer() {
            base.Channel.ResetTimer();
        }
        
        public void Move() {
            base.Channel.Move();
        }
        
        public void FinishStation(string stationName) {
            base.Channel.FinishStation(stationName);
        }
        
        public int GetState() {
            return base.Channel.GetState();
        }
        
        public int GetCounter() {
            return base.Channel.GetCounter();
        }
        
        public void SetCounter(int value) {
            base.Channel.SetCounter(value);
        }
        
        public void SetCounterForever(int value) {
            base.Channel.SetCounterForever(value);
        }
        
        public StationClient.ServiceReference2.LineStationBase[] GetStations() {
            return base.Channel.GetStations();
        }
        
        public StationClient.ServiceReference2.LineStationBase[] GetStationsArray() {
            return base.Channel.GetStationsArray();
        }
        
        public void RemoveStation(string LineStationRemoveId) {
            base.Channel.RemoveStation(LineStationRemoveId);
        }
        
        public int PushStationButton(int StationIndex, string ControlKey) {
            return base.Channel.PushStationButton(StationIndex, ControlKey);
        }
        
        public string ReadStationButton(int StationIndex, string ControlKey) {
            return base.Channel.ReadStationButton(StationIndex, ControlKey);
        }
        
        public string ReadStationName(int StationIndex) {
            return base.Channel.ReadStationName(StationIndex);
        }
        
        public void SetOPCMode(bool mode, string OPCServerName) {
            base.Channel.SetOPCMode(mode, OPCServerName);
        }
        
        public bool GetOPCMode() {
            return base.Channel.GetOPCMode();
        }
        
        public string ReadProduct(int StationIndex) {
            return base.Channel.ReadProduct(StationIndex);
        }
        
        public StationClient.ServiceReference2.Frame ReadFrame() {
            return base.Channel.ReadFrame();
        }
        
        public StationClient.ServiceReference2.ProductBase[] GetProductStock() {
            return base.Channel.GetProductStock();
        }
        
        public StationClient.ServiceReference2.ProductBase[] GetProductBuffer() {
            return base.Channel.GetProductBuffer();
        }
        
        public StationClient.ServiceReference2.ProductBase[] GetStationBuffer(int stationId) {
            return base.Channel.GetStationBuffer(stationId);
        }
        
        public StationClient.ServiceReference2.StationRealtimeData[] ReadRealTimeData(int StationIndex) {
            return base.Channel.ReadRealTimeData(StationIndex);
        }
        
        public StationClient.ServiceReference2.StationRealtimeData[] ReadRealTimeDataForLine(int StationIndex) {
            return base.Channel.ReadRealTimeDataForLine(StationIndex);
        }
        
        public StationClient.ServiceReference2.LogistTailElem[] GetLogisticTails() {
            return base.Channel.GetLogisticTails();
        }
        
        public int GetSumStopTime() {
            return base.Channel.GetSumStopTime();
        }
        
        public void RestoreLine() {
            base.Channel.RestoreLine();
        }
        
        public void SetOPCRestarted() {
            base.Channel.SetOPCRestarted();
        }
        
        public void SetStationDayPlan(string stationName, int amount) {
            base.Channel.SetStationDayPlan(stationName, amount);
        }
        
        public void SetStationMonthPlan(string stationName, int amount) {
            base.Channel.SetStationMonthPlan(stationName, amount);
        }
        
        public void SetStationDayFact(string stationName, int amount) {
            base.Channel.SetStationDayFact(stationName, amount);
        }
        
        public void SetStationMonthFact(string stationName, int amount) {
            base.Channel.SetStationMonthFact(stationName, amount);
        }
        
        public StationClient.ServiceReference2.LogMessage[] GetMemLogData() {
            return base.Channel.GetMemLogData();
        }
        
        public StationClient.ServiceReference2.ClientInstruction GetClientInstruction() {
            return base.Channel.GetClientInstruction();
        }
        
        public void SetClientInstruction(int Mode, string ContentUrl) {
            base.Channel.SetClientInstruction(Mode, ContentUrl);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ILogistic")]
    public interface ILogistic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogistic/GetLogisticRequests", ReplyAction="http://tempuri.org/ILogistic/GetLogisticRequestsResponse")]
        StationClient.ServiceReference2.LogistRequestElem[] GetLogisticRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogistic/GetTails", ReplyAction="http://tempuri.org/ILogistic/GetTailsResponse")]
        StationClient.ServiceReference2.LogistTailElem[] GetTails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogistic/GetBatchesOnLine", ReplyAction="http://tempuri.org/ILogistic/GetBatchesOnLineResponse")]
        StationClient.ServiceReference2.LogistTailElem[] GetBatchesOnLine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogistic/GetLogisticInfo", ReplyAction="http://tempuri.org/ILogistic/GetLogisticInfoResponse")]
        StationClient.ServiceReference2.LogisticInfo GetLogisticInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogistic/ReadLogisticRealTimeData", ReplyAction="http://tempuri.org/ILogistic/ReadLogisticRealTimeDataResponse")]
        StationClient.ServiceReference2.StationRealtimeData[] ReadLogisticRealTimeData(int stationIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogisticChannel : StationClient.ServiceReference2.ILogistic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogisticClient : System.ServiceModel.ClientBase<StationClient.ServiceReference2.ILogistic>, StationClient.ServiceReference2.ILogistic {
        
        public LogisticClient() {
        }
        
        public LogisticClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogisticClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogisticClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogisticClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StationClient.ServiceReference2.LogistRequestElem[] GetLogisticRequests() {
            return base.Channel.GetLogisticRequests();
        }
        
        public StationClient.ServiceReference2.LogistTailElem[] GetTails() {
            return base.Channel.GetTails();
        }
        
        public StationClient.ServiceReference2.LogistTailElem[] GetBatchesOnLine() {
            return base.Channel.GetBatchesOnLine();
        }
        
        public StationClient.ServiceReference2.LogisticInfo GetLogisticInfo() {
            return base.Channel.GetLogisticInfo();
        }
        
        public StationClient.ServiceReference2.StationRealtimeData[] ReadLogisticRealTimeData(int stationIndex) {
            return base.Channel.ReadLogisticRealTimeData(stationIndex);
        }
    }
}
